### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bahuljain**

### CODE REVIEW

**Comment by bahuljain** [comment]
additional instructions for mongo db section

**Comment by prakhar1989** [comment]
> Please do not load the entire database in memory and then find the solution. Marks will not be given for that.

What's the need for this?

**Comment by bahuljain** [comment]
They could do a select \* on the database and load it in a dict... and then
filter it to get the solution..What's the point of that then?

On Thu, Feb 25, 2016 at 8:07 PM, Prakhar Srivastav <notifications@github.com

**Comment by prakhar1989** [comment]
Ah okay. That point was not coming across clearly.

**Comment by bahuljain** [comment]
acha, you can edit it to make it more clear.. or should i?

On Thu, Feb 25, 2016 at 8:48 PM, Prakhar Srivastav <notifications@github.com

**Comment by prakhar1989** [comment]
Merging this for now. We'll reword it later.

**Pull request merged**
